language: scala
dist: xenial
jdk:
- openjdk8
- openjdk11
sudo: false
script:
- sbt test
- git diff --exit-code # check scalariform
before_script:
- rm project/pgp.sbt && rm project/sbt-updates.sbt && rm project/sonatype.sbt
- git add . --all
