language: scala
dist: trusty
jdk:
- oraclejdk8
scala:
- 2.12.8
sudo: false
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
addons:
  postgresql: '9.3'
before_script:
- rm project/pgp.sbt && rm project/sbt-updates.sbt && rm project/sonatype.sbt
- git add . --all
- psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
- psql -c "CREATE DATABASE scalikejdbc;" -U postgres
- psql -c "CREATE DATABASE scalikejdbc2;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;'
  -uroot
- mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
