language: scala
dist: xenial
jdk:
- openjdk8
sudo: false
script:
- sbt compile test:compile test
before_script:
- rm project/pgp.sbt && rm project/sbt-updates.sbt && rm project/sonatype.sbt
- git add . --all
