name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: olafurpg/setup-scala@v13
      with:
        # TODO https://github.com/scalikejdbc/scalikejdbc-async/issues/162
        java-version: "adopt@1.8.0-282"
    - uses: coursier/cache-action@v6
    - run: docker images
    - run: sbt -v test
    - run: docker images
